#!/bin/bash -l

#SBATCH -A uppmax2022-2-5 
#SBATCH -M snowy 
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 02:00:00
#SBATCH -J quast.job

# Load modules
module load bioinfo-tools
module load quast

# 

mkdir -p /home/mildo141/ga/Dead-sea/output/quast

OUT=/home/mildo141/ga/Dead-sea/output/quast

metaquast.py /home/mildo141/ga/Dead-sea/output/megahit/SRR4342129_assembly.contigs/final.contigs.fa -o $OUT/SRR4342129_qc
metaquast.py /home/mildo141/ga/Dead-sea/output/megahit/SRR4342133_assembly.contigs/final.contigs.fa -o $OUT/SRR4342133_qc
