#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 03:00:00
#SBATCH -J 04_bwa29.job
#SBATCH --mail-user milena.doroszko.0019@student.uu.se
#SBATCH --mail-type=ALL

#to help identify the work
cat $0
echo QOS = $SLURM_QOS
set -x


# Load modules
module load bioinfo-tools
module load bwa/0.7.17
module load samtools/1.14
module load MetaBat/2.12.1

#check which modules were loaded
module list
mkdir -p /home/mildo141/ga/output/04_bwaDNA
mkdir -p /home/mildo141/ga/output/04_bwaDNA/SRR4342129
mkdir -p /home/mildo141/ga/output/03_metabat/SRR4342129
mkdir -p /home/mildo141/ga/output/03_metabat/SRR4342129/bins_normalized

#define directories
OUT=/home/mildo141/ga/output/04_bwaDNA/SRR4342129
OUTM=/home/mildo141/ga/output/03_metabat/SRR4342129/bins_normalized
IN=/home/mildo141/Dead-sea/raw_data/3_Thrash_2017/DNA_trimmed


REF33=/home/mildo141/ga/output/02_megahit/SRR4342129_assembly.contigs/final.contigs.fa



bwa index $REF33
bwa mem -t 2 $REF33 $IN/SRR4342129_1.paired.trimmed.fastq.gz $IN/SRR4342129_2.paired.trimmed.fastq.gz | samtools sort -o $OUT/SRR4342129.bam

jgi_summarize_bam_contig_depths --outputDepth $OUTM/depth.txt --pairedContigs $OUTM/paired.txt $OUT/*.bam

#run metabat after normalization to sequencing depth
metabat -i $REF33 -a $OUTM/depth.txt -p $OUTM/paired.txt -o $OUTM/bin29 --specific -l -v --saveTNF $OUTM/saved.tnf --saveDistance $OUTM/saved.gprob

