#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J megahitRNA.job
#SBATCH -t 18:00:00

# Load modules
module load bioinfo-tools
module load megahit


#check which modules were loaded
module list

#define direcories
DIRDATA=/home/mildo141/ga/output/01_trimming
DIROUT=/home/mildo141/ga/output/02_megahit

#RNA_trim_37.LP.trim.fastq.gz  RNA_trim_37.RP.trim.fastq.gz  RNA_trim_39.LP.trim.fastq.gz  RNA_trim_39.RP.trim.fastq.gz  trim_D1.log
#RNA_trim_37.LU.trim.fastq.gz  RNA_trim_37.RU.trim.fastq.gz  RNA_trim_39.LU.trim.fastq.gz  RNA_trim_39.RU.trim.fastq.gz  trim_D3.log

# Create a directory
#mkdir -p /home/mildo141/ga/Dead-sea/output/megahit

megahit -1 $DIRDATA/RNA_trim_37.LP.trim.fastq.gz -2 $DIRDATA/RNA_trim_37.RP.trim.fastq.gz -o $DIROUT/SRR4342137R_assembly.contigs
megahit -1 $DIRDATA/RNA_trim_39.LP.trim.fastq.gz  -2 $DIRDATA/RNA_trim_39.RP.trim.fastq.gz -o $DIROUT/SRR4342139R_assembly.contigs

