#!/bin/bash -l

#SBATCH -A uppmax2022-2-5 
#SBATCH -M snowy 
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:00:00
#SBATCH -J quast.job

# Load modules
module load bioinfo-tools
module load quast

OUT=/home/mildo141/ga/output/02_quast

metaquast.py /home/mildo141/ga/output/02_megahit/SRR4342137R_assembly.contigs/final.contigs.fa -o $OUT/SRR4342137R_qc
metaquast.py /home/mildo141/ga/output/02_megahit/SRR4342139R_assembly.contigs/final.contigs.fa -o $OUT/SRR4342139R_qc

