#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 03:00:00
#SBATCH -J 04_bwa39.job
#SBATCH --mail-user milena.doroszko.0019@student.uu.se
#SBATCH --mail-type=ALL

#to help identify the work
cat $0
echo QOS = $SLURM_QOS
set -x

# Load modules
module load bioinfo-tools
module load bwa/0.7.17
module load samtools/1.14

#check which modules were loaded
module list
mkdir -p /home/mildo141/ga/output/04_bwaRNA
mkdir -p /home/mildo141/ga/output/04_bwaRNA/SRR4342139

#define directories
OUT=/home/mildo141/ga/output/04_bwaRNA/SRR4342139
IN=/home/mildo141/ga/output/01_trimming

REF33="/home/mildo141/ga/output/03_metabat/SRR4342133/bins_normalized"

cd /home/mildo141/ga/output/03_metabat/SRR4342133/bins_normalized

for sample in 1 2 3 4 5 6 7 8 11 13 14 15 16 17 18 19 20 21 22 23 26 27 28 31 32 33 34 35 36 37 40 41 43 44 45 46 47 48 49 51 52
do
   bwa index $REF33/bin33.${sample}.fa
   bwa mem -t 2 $REF33/bin33.${sample}.fa $IN/RNA_trim_39.LP.trim.fastq.gz $IN/RNA_trim_39.RP.trim.fastq.gz | samtools sort -@ 2 -o $OUT/bin33.${sample}_39.bam
done

