#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 12:00:00
#SBATCH -J bwaDNA.job
#SBATCH --mail-user milena.doroszko.0019@student.uu.se
#SBATCH --mail-type=ALL

#to help identify the work
cat $0
echo QOS = $SLURM_QOS
set -x

# Load modules
module load bioinfo-tools
module load bwa
module load samtools

#check which modules were loaded
module list

# Make directory for the output

mkdir -p /home/mildo141/ga/output/05_bwaDNA

#define directories
OUT=/home/mildo141/ga/output/05_bwaDNA
IN=/home/mildo141/Dead-sea/raw_data/3_Thrash_2017/DNA_trimmed
REF=/home/mildo141/ga/output/03_metabat
INDEX=/home/mildo141/ga/output/megahit/combi_assembly.contigs

#DNA files SRR4342129_1.paired.trimmed.fastq.gz  SRR4342129_2.paired.trimmed.fastq.gz  SRR4342133_1.paired.trimmed.fastq.gz  SRR4342133_2.paired.trimmed.fastq.gz

#there are 26 bins

for sample in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26;
do
        bwa index $INDEX/final.contigs.fa
        bwa mem -t 2 $REF/combi_binning.{sample}.fa  $IN/RR4342129_1.paired.trimmed.fastq.gz $IN/SRR4342129_2.paired.trimmed.fastq.gz $OUT/{sample}_SRR4342129.sam
        samtools view -S -b $OUT/{sample}_SRR4342129.sam -o $OUT/{sample}_SRR4342129.bam
        bwa mem -t 2 $REF/combi_binning.{sample}.fa  $IN/RR4342133_1.paired.trimmed.fastq.gz $IN/SRR4342133_2.paired.trimmed.fastq.gz $OUT/{sample}_SRR4342133.sam
        samtools view -S -b $OUT/{sample}_SRR4342133.sam -o $OUT/{sample}_SRR4342133.bam
done
*
#remove the sam files
rm $OUT/*.sam
